[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/rodiniz/BuscaCepGo"
  GO111MODULE = "on"
 
 [[redirects]]
  from = "/location/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200